/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class JMidiTriggerAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    JMidiTriggerAudioProcessorEditor (JMidiTriggerAudioProcessor&);
    ~JMidiTriggerAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
	void resized() override;
	void showFileDialogue();

	//String currentStatus = "";

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    JMidiTriggerAudioProcessor& processor;

	TextButton selectFileButton;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (JMidiTriggerAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
